apiVersion: v1
kind: Service
metadata:
  name: slacker-8081
  labels:
    app: slacker
    stack: java
spec:
  selector:
    app: slacker
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  type: LoadBalancer
